import type { Transaction } from "./types"

export const sampleTransactions: Transaction[] = [
  {
    id: "1",
    description: "Monthly Salary",
    amount: 5000,
    type: "income",
    category: "salary",
    date: "2026-01-15",
  },
  {
    id: "2",
    description: "Freelance Project",
    amount: 1200,
    type: "income",
    category: "freelance",
    date: "2026-01-12",
  },
  {
    id: "3",
    description: "Stock Dividends",
    amount: 350,
    type: "income",
    category: "investments",
    date: "2026-01-10",
  },
  {
    id: "4",
    description: "Grocery Shopping",
    amount: 285,
    type: "expense",
    category: "food",
    date: "2026-01-18",
  },
  {
    id: "5",
    description: "Electric Bill",
    amount: 120,
    type: "expense",
    category: "utilities",
    date: "2026-01-16",
  },
  {
    id: "6",
    description: "Gas & Transport",
    amount: 95,
    type: "expense",
    category: "transport",
    date: "2026-01-14",
  },
  {
    id: "7",
    description: "Netflix Subscription",
    amount: 15.99,
    type: "expense",
    category: "entertainment",
    date: "2026-01-13",
  },
  {
    id: "8",
    description: "New Headphones",
    amount: 199,
    type: "expense",
    category: "shopping",
    date: "2026-01-11",
  },
  {
    id: "9",
    description: "Gym Membership",
    amount: 45,
    type: "expense",
    category: "health",
    date: "2026-01-08",
  },
  {
    id: "10",
    description: "Side Gig Payment",
    amount: 400,
    type: "income",
    category: "other-income",
    date: "2026-01-05",
  },
  {
    id: "11",
    description: "Restaurant Dinner",
    amount: 78,
    type: "expense",
    category: "food",
    date: "2026-01-20",
  },
  {
    id: "12",
    description: "Internet Bill",
    amount: 65,
    type: "expense",
    category: "utilities",
    date: "2026-01-19",
  },
]

export const monthlyData = [
  { month: "Aug", income: 5800, expenses: 3200 },
  { month: "Sep", income: 6200, expenses: 3500 },
  { month: "Oct", income: 5500, expenses: 3100 },
  { month: "Nov", income: 6800, expenses: 3800 },
  { month: "Dec", income: 7200, expenses: 4200 },
  { month: "Jan", income: 6950, expenses: 903 },
]

export const categoryLabels: Record<string, string> = {
  salary: "Salary",
  freelance: "Freelance",
  investments: "Investments",
  "other-income": "Other Income",
  food: "Food & Dining",
  gas: "Gas",
  repair: "Repair",
  electricity: "Electricity",
  water: "Water",
  internet: "Internet",
  phone: "Phone",
  "other-utilities": "Other Utilities",
  entertainment: "Entertainment",
  shopping: "Shopping",
  health: "Health",
  "other-expense": "Other Expense",
}

export const categoryIcons: Record<string, string> = {
  salary: "💼",
  freelance: "💻",
  investments: "📈",
  "other-income": "💰",
  food: "🍔",
  gas: "⛽",
  repair: "🔧",
  electricity: "⚡",
  water: "💧",
  internet: "🌐",
  phone: "📱",
  "other-utilities": "🔌",
  entertainment: "🎬",
  shopping: "🛍️",
  health: "🏥",
  "other-expense": "📦",
}
